### PR TITLE
Add Sensekeys

### PR DESCRIPTION
**Pull request by oxinabox**
Sometimes -- often, corpora annotate senses with the wordnet's [Sensekeys.
](https://wordnet.princeton.edu/man/senseidx.5WN.html#sect3)

I have added these to the package.

They are useful when dealing with corpora such as, SemCor. and various semeval tasks eg SemEval 2007 task7.

Right now this is a one-way map -- that is to say that given a Synset and a Lemma,  there is a method to produce its Sense Key.

I might make a method to go the other way; if I find it will be useful.

### CODE REVIEW

**Comment by oxinabox** [comment]
I suggest that at this point in Julia's progression maintaining support in new tagged version of packages for 0.3, is more work than it is worth.
Since 0.5 is about to be released (it is in rc3).
Things that were deprecated in 0.4 and now gone.

**Comment by jbn** [comment]
@oxinabox I haven't got a chance to look at this yet. I put it on my calendar for Wednesday (along with your #1. Thanks for the PR. Furthermore, I agree, 0.3 is no longer worth it.

**Comment by oxinabox** [comment]
@jbn No rush. Take your time.  
Do take the time to review it well, I'm by no means perfect.
Particularly at working with other people's code.

I have my own branch checked out for my use.
So I personally am not harmed by waiting.

**Comment by jbn** [comment]
LGTM. I'm gonna change some things stylistically and squash the commits. But, thanks!

**Pull request merged**
